import questGen

print(questGen.get_theme())
print(questGen.get_theme())
print(questGen.get_theme())
print(questGen.get_theme())
print(questGen.get_theme())
print(questGen.get_theme())
print(questGen.get_theme())
print(questGen.get_theme())
print(questGen.get_theme())
print(questGen.get_theme())
print(questGen.get_theme())
print(questGen.get_theme())
print(questGen.get_theme())
print(questGen.get_theme())
print(questGen.get_theme())